[project]
name = 'decen_exchange'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.den_exchange]
path = 'contracts/den_exchange.clar'
clarity_version = 3
epoch = 'latest'

[contracts.test-token-a]
path = 'contracts/test-token-a.clar'
clarity_version = 3
epoch = 'latest'

[contracts.test-token-b]
path = 'contracts/test-token-b.clar'
clarity_version = 3
epoch = 'latest'

[contracts.test-token-c]
path = 'contracts/test-token-c.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
